name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python test.py

    - name: Send WebEx Notification for CI/CD Results
      run: |
        python -c 'import requests; requests.post("https://webexapis.com/v1/messages", json={"roomId":"YOUR_ROOM_ID","text":"CI/CD pipeline execution completed!"}, headers={"Authorization":"Bearer YOUR_ACCESS_TOKEN"})'

